export const BaseUrl = 'https://vegurban.com/admin/' + 'api-firebase/';

export const Constant = {
  MainBaseURL: 'https://vegurban.com/admin/', //Admin panel url
  WebsiteUrl: 'https://vegurban.com/',
  JWT_KEY:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ',
  GRID_COLUMN: 3, //Category View Number Of Grid Per Line
  LOAD_ITEM_LIMIT: 10, //Load items limit in listing ,Maximum load item once

  PLAY_STORE_LINK: 'https://play.google.com/store/apps/details?id=',
  PLAY_STORE_RATE_US_LINK: 'market://details?id=',

  //**********APIS**********
  FAQ_URL: BaseUrl + 'get-faqs.php',
  CategoryUrl: BaseUrl + 'get-categories.php',
  Get_RazorPay_OrderId: BaseUrl + 'create-razorpay-order.php',
  SubcategoryUrl: BaseUrl + 'get-subcategories-by-category-id.php',
  GET_SECTION_URL: BaseUrl + 'sections.php',
  GET_ADDRESS_URL: BaseUrl + 'user-addresses.php',
  RegisterUrl: BaseUrl + 'user-registration.php',
  PAPAL_URL: MainBaseURL + 'paypal/create-payment.php',
  LoginUrl: BaseUrl + 'login.php',
  GET_ALL_DATA_URL: BaseUrl + 'get-all-data.php',
  GET_ALL_PRODUCTS_URL: BaseUrl + 'get-all-products.php',
  GET_QR_CODE: BaseUrl + 'update_qr_code.php',
  PRODUCT_SEARCH_URL: BaseUrl + 'products-search.php',
  SETTING_URL: BaseUrl + 'settings.php',
  GET_PRODUCT_BY_SUB_CATE: BaseUrl + 'get-products-by-subcategory-id.php',
  GET_PRODUCT_BY_CATE: BaseUrl + 'get-products-by-category-id.php',
  GET_FAVORITES_URL: BaseUrl + 'favorites.php',
  GET_OFFLINE_FAVORITES_URL: BaseUrl + 'get-products-offline.php',
  MIDTRANS_PAYMENT_URL: MainBaseURL + 'midtrans/create-payment.php',
  GET_OFFLINE_CART_URL: BaseUrl + 'get-variants-offline.php',
  GET_PRODUCT_DETAIL_URL: BaseUrl + 'get-product-by-id.php',
  CITY_URL: BaseUrl + 'get-cities.php',
  GET_AREA_BY_CITY: BaseUrl + 'get-areas-by-city-id.php',
  ORDER_PROCESS_URL: BaseUrl + 'order-process.php',
  USER_DATA_URL: BaseUrl + 'get-user-data.php',
  CART_URL: BaseUrl + 'cart.php',
  STRIPE_BASE_URL: MainBaseURL + 'stripe/create-payment.php',
  GET_SIMILAR_PRODUCT_URL: BaseUrl + 'get-similar-products.php',
  TRANSACTION_URL: BaseUrl + 'get-user-transactions.php',
  PROMO_CODE_CHECK_URL: BaseUrl + 'validate-promo-code.php',
  VERIFY_PAYMENT_REQUEST: BaseUrl + 'payment-request.php',
  REGISTER_DEVICE_URL: BaseUrl + 'store-fcm-id.php',
  FLASH_SALES_URL: BaseUrl + 'flash-sales.php',

  //**************parameters***************
  VERIFY_PAY_STACK: 'verify_paystack_transaction',
  DISCOUNTED_AMOUNT: 'discounted_amount',
  AccessKey: 'accesskey',
  VALIDATE_PROMO_CODE: 'validate_promo_code',
  AccessKeyVal: '90336',
  PROFILE: 'profile',
  UPLOAD_PROFILE: 'upload_profile',
  GetVal: '1',
  GROSS_AMOUNT: 'gross_amount',
  AUTHORIZATION: 'Authorization',
  PARAMS: 'params',
  GET_PRIVACY: 'get_privacy',
  GET_TERMS: 'get_terms',
  GET_ADDRESSES: 'get_addresses',
  DELETE_ADDRESS: 'delete_address',
  ADD_ADDRESS: 'add_address',
  UPDATE_ADDRESS: 'update_address',
  GET_CONTACT: 'get_contact',
  GET_ABOUT_US: 'get_about_us',
  NEW_BALANCE: 'new_balance',
  ADD_TO_FAVORITES: 'add_to_favorites',
  REMOVE_FROM_FAVORITES: 'remove_from_favorites',
  CANCELLED: 'cancelled',
  GET_NOTIFICATIONS: 'get-notifications',
  GET_ALL_FLASH_SALES: 'get-all-flash-sales',
  GET_ALL_FLASH_SALES_PRODUCTS: 'get-all-flash-sales-products',
  RETURNED: 'returned',
  GET_USER_DATA: 'get_user_data',
  KEY_BALANCE: 'balance',
  AWAITING_PAYMENT: 'awaiting_payment',
  KEY_WALLET_USED: 'wallet_used',
  KEY_WALLET_BALANCE: 'wallet_balance',
  WALLET: 'wallet',
  PAYMENT: 'payment',
  REDIRECT_URL: 'redirect_url',
  URL: 'url',
  ADD_MULTIPLE_ITEMS: 'add_multiple_items',
  SAVE_FOR_LATER_ITEMS: 'save_for_later_items',
  GET_REORDER_DATA: 'get_reorder_data',
  FIRST_NAME: 'first_name',
  LAST_NAME: 'last_name',
  PAYER_EMAIL: 'payer_email',
  COUNTRY_CODE: 'country_code',
  COUNTRY: 'country',
  IS_DEFAULT: 'is_default',
  ITEM_NAME: 'item_name',
  ITEM_NUMBER: 'item_number',
  UPDATE_ORDER_ITEM_STATUS: 'update_order_item_status',
  ADD_PRODUCT_REVIEW: 'add_products_review',
  ORDER_ITEM_ID: 'order_item_id',
  PAYMENT_METHODS: 'payment_methods',
  PAY_M_KEY: 'payumoney_merchant_key',
  PAYU_M_ID: 'payumoney_merchant_id',
  PAYU_SALT: 'payumoney_salt',
  RAZOR_PAY_KEY: 'razorpay_key',
  pay_stack_public_key: 'paystack_public_key',
  UNREAD_NOTIFICATION_COUNT: 'unread_notification_count',
  UNREAD_WALLET_COUNT: 'unread_wallet_count',
  UNREAD_TRANSACTION_COUNT: 'unread_transaction_count',
  flutter_wave_public_key: 'flutterwave_public_key',
  flutter_wave_secret_key: 'flutterwave_secret_key',
  flutter_wave_encryption_key: 'flutterwave_encryption_key',
  flutter_wave_currency_code: 'flutterwave_currency_code',
  CITY_ID: 'city_id',
  CITY: 'city',
  AREA_ID: 'area_id',
  REFERRAL_CODE: 'referral_code',
  FRIEND_CODE: 'friends_code',
  SOLD_OUT_TEXT: 'Sold Out',
  QTY: 'qty',
  GET_USER_CART: 'get_user_cart',
  DELETE_ORDER: 'delete_order',
  GET_USER_TRANSACTION: 'get_user_transactions',
  TYPE_TRANSACTION: 'transactions',
  TYPE_WALLET_TRANSACTION: 'wallet_transactions',
  SUCCESS: 'success',
  FAILED: 'failed',
  PENDING: 'pending',
  CREDIT: 'credit',
  REMOVE_FROM_CART: 'remove_from_cart',
  SORT: 'sort',
  TYPE: 'type',
  IMAGE: 'image',
  IMAGES: 'image[]',
  NAME: 'name',
  TYPE_ID: 'type_id',
  ID: 'id',
  SHIPPED: 'shipped',
  RECEIVED: 'received',
  PROCESSED: 'processed',
  DELIVERED: 'delivered',
  SUBTITLE: 'subtitle',
  PRODUCTS: 'products',
  STATUS: 'status',
  REASON: 'reason',
  TITLE: 'title',
  SECTION_STYLE: 'style',
  SHORT_DESC: 'short_description',
  REGISTER: 'register',
  EMAIL: 'email',
  MOBILE: 'mobile',
  LOCAL_PICKUP: 'local_pickup',
  PICKUP: 'pickup',
  ALTERNATE_MOBILE: 'alternate_mobile',
  PASSWORD: 'password',
  FCM_ID: 'fcm_id',
  GET_ALL_PRODUCTS_NAME: 'get_all_products_name',
  IS_USER_LOGIN: 'is_user_login',
  PINCODE: 'pincode',
  STATE: 'state',
  ERROR: 'error',
  GET_TIMEZONE: 'get_timezone',
  ORDER_NOTE: 'order_note',
  VERIFY_USER: 'verify-user',
  USER_ID: 'user_id',
  ADD_WALLET_BALANCE: 'add_wallet_balance',
  TAX_AMOUNT: 'tax_amount',
  TAX_PERCENT: 'tax_percentage',
  RATE: 'rate',
  REVIEW: 'review',
  EDIT_PROFILE: 'edit-profile',
  CHANGE_PASSWORD: 'change-password',
  CATEGORY_ID: 'category_id',
  SLIDER_IMAGES: 'slider_images',
  NEW_SLIDER_IMAGES: 'new_slider_images',
  CATEGORIES: 'categories',
  SECTIONS: 'sections',
  OFFER_IMAGES: 'offer_images',
  FLASH_SALES: 'flash_sales',
  SUB_CATEGORY_ID: 'subcategory_id',
  GET_ALL_PRODUCTS: 'get_all_products',
  GET_ALL_SECTIONS: 'get-all-sections',
  SECTION_ID: 'section_id',
  FLASH_SALES_ID: 'flash_sales_id',
  GET_FAVORITES: 'get_favorites',
  GET_FAVORITES_OFFLINE: 'get_products_offline',
  GET_CART_OFFLINE: 'get_variants_offline',
  PRODUCT_SEARCH: 'products-search',
  SEARCH: 'search',
  ADD_TRANSACTION: 'add_transaction',
  GET_PAYMENT_METHOD: 'get_payment_methods',
  GET_ORDERS: 'get_orders',
  CONTACT: 'contact',
  DATA: 'data',
  SAVE_FOR_LATER: 'save_for_later',
  PRODUCT_REVIEW: 'product_review',
  ITEMS: 'items',
  PRODUCT_ID: 'product_id',
  GET_SIMILAR_PRODUCT: 'get_similar_products',
  PRODUCT_IDs: 'product_ids',
  VARIANT_IDs: 'variant_ids',
  DISCOUNT: 'discount',
  SETTINGS: 'settings',
  GET_SETTINGS: 'get_settings',
  GET_TIME_SLOT_CONFIG: 'get_time_slot_config',
  TIME_SLOT_CONFIG: 'time_slot_config',
  IS_TIME_SLOTS_ENABLE: 'is_time_slots_enabled',
  DELIVERY_STARTS_FROM: 'delivery_starts_from',
  ALLOWED_DAYS: 'allowed_days',
  paypal_method: 'paypal_payment_method',
  payu_method: 'payumoney_payment_method',
  razor_pay_method: 'razorpay_payment_method',
  cod_payment_method: 'cod_payment_method',
  cod_mode: 'cod_mode',
  product: 'product',
  paystack_method: 'paystack_payment_method',
  flutter_wave_payment_method: 'flutterwave_payment_method',
  midtrans_payment_method: 'midtrans_payment_method',
  stripe_payment_method: 'stripe_payment_method',
  paytm_payment_method: 'paytm_payment_method',
  paytm_merchant_id: 'paytm_merchant_id',
  paytm_merchant_key: 'paytm_merchant_key',
  paytm_mode: 'paytm_mode',
  payumoney_mode: 'payumoney_mode',
  ssl_method: 'ssl_method',
  ssl_mode: 'ssl_mode',
  ssl_store_id: 'ssl_store_id',
  ssl_store_password: 'ssl_store_password',
  direct_bank_transfer_method: 'direct_bank_transfer_method',
  account_name: 'account_name',
  account_number: 'account_number',
  bank_name: 'bank_name',
  bank_code: 'bank_code',
  notes: 'notes',
  MINIMUM_AMOUNT: 'min_amount',
  CURRENCY: 'currency',
  GET_FAQS: 'get_faqs',
  LIMIT: 'limit',
  OFFSET: 'offset',
  LATITUDE: 'latitude',
  LONGITUDE: 'longitude',
  AMOUNT: 'amount',
  REFERENCE: 'reference',
  PROMO_DISCOUNT: 'promo_discount',
  TOTAL: 'total',
  NUMBER_OF_REVIEW: 'number_of_reviews',
  PRODUCT_VARIANT_ID: 'product_variant_id',
  QUANTITY: 'quantity',
  USER_NAME: 'user_name',
  DELIVERY_CHARGE: 'delivery_charge',
  DELIVERY_TIME: 'delivery_time',
  PAYMENT_METHOD: 'payment_method',
  ADDRESS: 'address',
  ADDRESS_LINE1: 'address_line1',
  POSTAL_CODE: 'postal_code',
  LANDMARK: 'landmark',
  TRANS_ID: 'txn_id',
  MESSAGE: 'message',
  FINAL_TOTAL: 'final_total',
  FROM: 'from',
  VARIANT_POSITION: 'variant_position',
  ORDER_ID: 'order_id',
  DELETE_BANK_TRANSFER_ATTACHMENT: 'delete_bank_transfers_attachment',
  UPLOAD_BANK_TRANSFER_ATTACHMENT: 'upload_bank_transfers_attachment',
  publishableKey: 'publishableKey',
  clientSecret: 'clientSecret',
  UPDATE_ORDER_STATUS: 'update_order_status',
  PLACE_ORDER: 'place_order',
  NEW: 'new',
  OLD: 'old',
  HIGH: 'high',
  LOW: 'low',
  SLUG: 'slug',
  GET_PRODUCT_REVIEW: 'get_product_reviews',
  PROMO_CODE: 'promo_code',
  filterValues: [
    ' Newest to Oldest ',
    ' Oldest to Newest ',
    ' Price Highest to Lowest ',
    ' Price Lowest to Highest ',
  ],
  CUST_ID: 'CUST_ID',
  ORDERID: 'ORDERID',
  STATUS_: 'STATUS',
  TXN_SUCCESS: 'TXN_SUCCESS',
  minimum_version_required: 'minimum_version_required',
  is_version_system_on: 'is_version_system_on',
  currency: 'currency',
  current_date: 'current_date',
  min_order_amount: 'min_order_amount',
  max_cart_items_count: 'max_cart_items_count',
  area_wise_delivery_charge: 'area_wise_delivery_charge',
  is_refer_earn_on: 'is_refer_earn_on',
  refer_earn_bonus: 'refer_earn_bonus',
  refer_earn_method: 'refer_earn_method',
  max_refer_earn_amount: 'max_refer_earn_amount',
  max_product_return_days: 'max_product_return_days',
  user_wallet_refill_limit: 'user_wallet_refill_limit',
  min_refer_earn_order_amount: 'min_refer_earn_order_amount',
  ratings: 'ratings',
  local_pickup: 'local_pickup',
  support_number: 'support_number',
  map_latitude: 'map_latitude',
  map_longitude: 'map_longitude',
  store_address: 'store_address',
  ALPHA_NUMERIC_STRING:
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghjiklmnopqrstuvwxyz',
  NUMERIC_STRING: '123456789',

  //**************Constants Values***************
  isCODAllow: true,
  TOOLBAR_TITLE: '',
  CURRENT_USER_LOCATION: '',
  selectedAddressId: '',
  DefaultAddress: '',
  DefaultCity: '',
  DefaultPinCode: '',
  SETTING_DELIVERY_CHARGE: 0.0,
  CURRENT_USER_LATITUDE: 0.0,
  CURRENT_USER_LONGITUDE: 0.0,
  SETTING_TAX: 0.0,
  SETTING_MINIMUM_AMOUNT_FOR_FREE_DELIVERY: 0.0,
  WALLET_BALANCE: 0.0,
  U_ID: '',
  //   public static HashMap<String, String> CartValues = new HashMap<>();
  selectedDatePosition: 0,
  CLICK: false,
  FLOAT_TOTAL_AMOUNT: 0.0,
  TOTAL_CART_ITEM: 0,
  isOrderCancelled: false,
  FRIEND_CODE_VALUE: '',
  PAYPAL: '',
  PAYUMONEY: '',
  RAZORPAY: '',
  COD: '',
  COD_MODE: '',
  PAY_STACK: '',
  FLUTTER_WAVE: '',
  MIDTRANS: '',
  STRIPE: '',
  MERCHANT_ID: '',
  MERCHANT_KEY: '',
  PAYTM_MERCHANT_ID: '',
  PAYTM: '',
  PAYTM_MERCHANT_KEY: '',
  PAYTM_MODE: '',
  PAYUMONEY_MODE: '',
  MERCHANT_SALT: '',
  RAZOR_PAY_KEY_VALUE: '',
  PAY_STACK_KEY: '',
  FLUTTER_WAVE_PUBLIC_KEY_VAL: '',
  FLUTTER_WAVE_SECRET_KEY_VAL: '',
  FLUTTER_WAVE_ENCRYPTION_KEY_VAL: '',
  FLUTTER_WAVE_CURRENCY_CODE_VAL: '',
  SSLECOMMERZ: '',
  SSLECOMMERZ_MODE: '',
  SSLECOMMERZ_STORE_ID: '',
  SSLECOMMERZ_SECRET_KEY: '',
  DIRECT_BANK_TRANSFER: '',
  ACCOUNT_NAME: '',
  ACCOUNT_NUMBER: '',
  BANK_NAME: '',
  BANK_CODE: '',
  NOTES: '',

  STRIPE_PUBLISHABLE_KEY: '',
};
